services:
  client:
    ports:
      - "8080:8080"
  
  server:
    ports:
      - "8000:8000"
      - "5678:5678"
  
  postgres:
    ports:
      - "5432:5432"
  
  redis:
    ports:
      - "6379:6379"
