# Main webapp process
web: PYTHONPATH=./server daphne -b 0.0.0.0 -p $PORT {{ cookiecutter.project_slug }}.asgi:application

# Update DB schema for any changes
release: python server/manage.py migrate --noinput
