[tox]
skipsdist = true
envlist = py39,ruff-template

[testenv]
deps = -rrequirements.txt
commands = pytest {posargs:./tests}

[testenv:ruff-template]
deps = ruff
commands = ruff format --check hooks tests setup.py scripts
