name: Linter
on: [push]
jobs:
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Run Ruff Lint Check
        run: uv run ruff check --output-format=github server
      - name: Run Ruff Format Check
        run: uv run ruff format --check server -q
{%- if cookiecutter.client_app == 'React' %}
  Lint_Web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: 📦 Install dependencies
        env:
          NPM_CONFIG_PRODUCTION: false
        working-directory: ./client
        run: |
          npm install
      - name: 🆎 TypeCheck
        working-directory: ./client
        run: npm run tslint
      - name: 🚧 ESLint
        working-directory: ./client
        run: npm run eslint
      - name: 🎨 Prettier
        working-directory: ./client
        run: npm run format:check
{%- endif %}
{%- if cookiecutter.include_mobile == 'y' %}
  Lint_Mobile:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: 📦 Install dependencies
        working-directory: ./mobile
        run: npm install
      - name: 🆎 TypeCheck
        working-directory: ./mobile
        run: npm run lint:tslint
      - name: 🚧 ESLint
        working-directory: ./mobile
        run: npm run lint:eslint
      - name: 🎨 Prettier
        working-directory: ./mobile
        run: npm run format:check
{%- endif %}
