name: Unit Tests 
on: [push]
jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: {{ "${{ secrets.SECRET_KEY }}" }}
    steps:
      - uses: actions/checkout@v2
      - run: pipx install pipenv
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pipenv'
      - run: pipenv install --dev --deploy
      - run: pipenv run pytest --mccabe --cov={{ cookiecutter.project_slug }} -vv server/{{ cookiecutter.project_slug }}
      - run: pipenv run coverage report --fail-under=20
