name: 'Upload to Google Docs'
description: 'Creates or updates a Google Doc from a file.'
inputs:
  credentials:
    description: 'The Google Cloud service account credentials JSON.'
    required: true
  file-path:
    description: 'The path to the file to upload.'
    required: true
  document-id:
    description: 'The ID of the Google Doc to update. If not provided, a new one is created.'
    required: false
  folder-id:
    description: 'The ID of the Google Drive folder to create the new document in.'
    required: false
  document-title:
    description: 'The title of the new Google Doc. Defaults to the filename.'
    required: false
outputs:
  documentId:
    description: 'The ID of the created or updated document.'
  webViewLink:
    description: 'A link to view the document in the browser.'
runs:
  using: 'node16'
  main: 'index.js'
