#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


[ -d "/client/dist" ] && python manage.py collectstatic --noinput || echo "Client Folder not built skipping collect static"

python manage.py migrate

gunicorn {{ cookiecutter.project_slug }}.asgi:application \
  -k uvicorn.workers.UvicornWorker \
  --bind 0.0.0.0:${PORT:-8000} \
  --workers ${WEB_CONCURRENCY:-2} \
  --timeout ${GUNICORN_TIMEOUT:-120} \
  --access-logfile - \
  --error-logfile -
