# Terraform Backend Configuration
# Generated by setup_backend.sh

bucket         = "aws-sample-tf-state"
key            = "pari-test-app/development/terraform.tfstate"
region         = "us-east-1"
dynamodb_table = "aws-sample-tf-state-lock"
encrypt        = true
