# Generated by Django 4.2.15 on 2024-08-16 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import {{ cookiecutter.project_slug }}.core.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserResetPasswordCodeMessages",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=255)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reset_password_codes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
            managers=[
                ("objects", {{ cookiecutter.project_slug }}.core.models.UserResetPasswordCodeMessagesManager()),
            ],
        ),
    ]
